### ISSUE TITLE
can i modify these to make my own brickbattle game

### ISSUE THREAD

**Issue by ctrl-shift-make** [SharkBloxYT/Old-Roblox-Game-Backup#2]
Hi @SharkBloxYT.
I was thinking on making my own brickbattle game. 
Can I use these?
Also is there any working version of brickbattle tools

**Comment by SharkBloxYT** [comment]
Of course use them however you like. They are uncoplocked free for use by
the official roblox account :)

On Tuesday, November 2, 2021, Rocky ***@***.***> wrote:
> Hi @SharkBloxYT.
> I was thinking on making my own brickbattle game.
> Can I use these?
> Also is there any working version of brickbattle tools
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. <
https://ci4.googleusercontent.com/proxy/bT3-VEZl0kFDWoz4S_AdO8jAjKvFOfXp5alZnbO84u63pPRCbDW5_CoNd8sLhFJJ-Exb5_Dakg-8ZS6GQwWHs0OZ_zdzjLS0EV3MvgtCfK_JEKFD1nOxwW6XOJcy35IL4qWblHcj7d1KIuo2kSNf1pEXNKfde1jcN6wXZ8JCxWggv5RY35DT9qAmuX7k28irWM3MMw6_dZnsEfQCSfNvowAPUJ8=s0-d-e1-ft#https://github.com/notifications/beacon/AWJCOL5LB7HWWA2SHVJZ333UJ5LKDA5CNFSM5HFOJ6AKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4PQZKQYQ.gif>

**Comment by ctrl-shift-make** [comment]
@SharkBloxYT What about a working brickbattle tools set?
